"""add_cpf_and_vinculo_to_usuario

Revision ID: 226dea51fb05
Revises: 85d79b471ed2
Create Date: 2025-12-04 16:51:55.210163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '226dea51fb05'
down_revision: Union[str, Sequence[str], None] = '85d79b471ed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite supports ADD COLUMN natively
    op.add_column('usuarios', sa.Column('cpf', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('vinculo', sa.String(), nullable=True))
    
    # Use batch mode only for the unique constraint which requires table recreation
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_usuarios_cpf', ['cpf'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint('uq_usuarios_cpf', type_='unique')
        batch_op.drop_column('vinculo')
        batch_op.drop_column('cpf')
    # ### end Alembic commands ###
