"""add_tema_to_curso

Revision ID: 6d27f6d672b3
Revises: 226dea51fb05
Create Date: 2025-12-04 19:05:13.701173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d27f6d672b3'
down_revision: Union[str, Sequence[str], None] = '226dea51fb05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cursos', sa.Column('tema', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cursos', 'tema')
    # ### end Alembic commands ###
