"""create_capacitacoes_tables

Revision ID: 6fd667d2e7fa
Revises: 8a2efbe37bb6
Create Date: 2025-11-10 16:33:43.295571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fd667d2e7fa'
down_revision: Union[str, Sequence[str], None] = '8a2efbe37bb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificados',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('validado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cursos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('certificadora', sa.String(), nullable=True),
    sa.Column('carga_horaria', sa.Integer(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('ano_gd', sa.Enum('ANO_2024', 'ANO_2025', 'ANO_2026', name='anogd'), nullable=True),
    sa.Column('chefia_id', sa.String(), nullable=False),
    sa.Column('lotacao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('perfil', sa.Enum('TRABALHADOR', 'CHEFIA', 'UDP', name='perfilusuario'), nullable=False),
    sa.Column('lotacao', sa.String(), nullable=True),
    sa.Column('nome_chefia', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atribuicoes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('curso_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'REALIZADO', 'VALIDADO', 'RECUSADO', name='statusatribuicao'), nullable=False),
    sa.Column('certificado_id', sa.String(), nullable=True),
    sa.Column('data_atribuicao', sa.DateTime(), nullable=False),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.Column('data_validacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['certificado_id'], ['certificados.id'], ),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atribuicoes')
    op.drop_table('usuarios')
    op.drop_table('cursos')
    op.drop_table('certificados')
    # ### end Alembic commands ###
