"""add_atribuir_a_todos_to_curso

Revision ID: 7668b8cb0e9f
Revises: a60210d64ffe
Create Date: 2025-11-13 15:13:35.354861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7668b8cb0e9f'
down_revision: Union[str, Sequence[str], None] = 'a60210d64ffe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cursos', sa.Column('atribuir_a_todos', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cursos', 'atribuir_a_todos')
    # ### end Alembic commands ###
