"""change_curso_anogd_to_string

Revision ID: 96f1ed75e1ad
Revises: 594a754f2d86
Create Date: 2025-11-12 19:14:35.517314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96f1ed75e1ad'
down_revision: Union[str, Sequence[str], None] = '594a754f2d86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cursos', schema=None) as batch_op:
        batch_op.alter_column('ano_gd',
               existing_type=sa.Enum('ANO_ATUAL', 'ANO_ANTERIOR', name='anogd'),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cursos', schema=None) as batch_op:
        batch_op.alter_column('ano_gd',
               existing_type=sa.String(length=255),
               type_=sa.Enum('ANO_ATUAL', 'ANO_ANTERIOR', name='anogd'),
               existing_nullable=True)
    # ### end Alembic commands ###
