"""create_inscricoes_table

Revision ID: b0a58a5187a3
Revises: 7085edd37e66
Create Date: 2025-11-11 16:39:03.954648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0a58a5187a3'
down_revision: Union[str, Sequence[str], None] = '7085edd37e66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cursos', schema=None) as batch_op:
        batch_op.alter_column('lotacao',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cursos', schema=None) as batch_op:
        batch_op.alter_column('lotacao',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
    # ### end Alembic commands ###
