"""add_details_to_curso

Revision ID: f731a871de84
Revises: 6d27f6d672b3
Create Date: 2025-12-05 19:15:08.988364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f731a871de84'
down_revision: Union[str, Sequence[str], None] = '6d27f6d672b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cursos', sa.Column('conteudista', sa.String(), nullable=True))
    op.add_column('cursos', sa.Column('disponibilidade_dias', sa.Integer(), nullable=True))
    op.add_column('cursos', sa.Column('tipo_oferta', sa.String(), nullable=True))
    op.add_column('cursos', sa.Column('apresentacao', sa.Text(), nullable=True))
    op.add_column('cursos', sa.Column('publico_alvo', sa.Text(), nullable=True))
    op.add_column('cursos', sa.Column('conteudo_programatico', sa.Text(), nullable=True))
    op.add_column('cursos', sa.Column('data_lancamento', sa.String(), nullable=True))
    op.add_column('cursos', sa.Column('acessibilidade', sa.String(), nullable=True))
    op.add_column('cursos', sa.Column('observacao', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cursos', 'observacao')
    op.drop_column('cursos', 'acessibilidade')
    op.drop_column('cursos', 'data_lancamento')
    op.drop_column('cursos', 'conteudo_programatico')
    op.drop_column('cursos', 'publico_alvo')
    op.drop_column('cursos', 'apresentacao')
    op.drop_column('cursos', 'tipo_oferta')
    op.drop_column('cursos', 'disponibilidade_dias')
    op.drop_column('cursos', 'conteudista')
    # ### end Alembic commands ###
